### ISSUE TITLE
缺少上次重置时间

### ISSUE THREAD

**Issue by Tardisyuan** [renhai-lab/sgcc_electricity#11]
## 缺少上次重置时间
以下实体的状态类别虽然是 `measurement`，但缺少 `last_reset` 参数：
· sensor.last_electricity_usage_entity

以上是我将last_electricity_usage_entity放入能源 电力 出现的报错
![配置 – Home Assistant - Google Chrome 2023_8_18 22_55_52](https://github.com/renhaiidea/sgcc_electricity/assets/66050966/e185a261-c083-4998-8cff-9e67d4e8dd94)

**Comment by bobwng** [comment]
> template配置文件没有修改

@Tardisyuan 您能给一个示例吗？

**Comment by Tardisyuan** [comment]
![屏幕截图(1)](https://github.com/renhaiidea/sgcc_electricity/assets/66050966/177dd8e3-fde7-41b9-8f28-e6de3b005859)
这是参考实体的，没做修改。

在有实体有数据的条件下 按第一张截图的方式在电力公司将last_electricity_usage_entity放入消耗电能 就会出现的报错：缺少 last_reset 参数

**Comment by bobwng** [comment]
> 在有实体有数据的条件下 按第一张截图的方式在电力公司将last_electricity_usage_entity放入消耗电能 就会出现的报错：缺少 last_reset 参数

抱歉，理解错了。我也碰到同样问题，还以为您在上面提出了解决方案。;)

**Comment by renhai-lab** [comment]
我也会报错，但是可以正常使用。

**Comment by Tardisyuan** [comment]
你能源这边能正常显示吗？

**Comment by renhai-lab** [comment]
我之前理解错了，放入能源面板需要将修复state_class的问题：`measurement`应该改为`total_increasing`，应该能解决问题，还待进一步测试：
```

  - trigger:
      - platform: event
        event_type: "state_changed"
        event_data:
          entity_id: sensor.last_electricity_usage
    sensor:
      - name: 国网最近一天用电量
        unique_id: last_electricity_usage_entity
        state: "{{ states('sensor.last_electricity_usage') }}"
        attributes: 
          present_date: "{{ state_attr('sensor.last_electricity_usage', 'present_date') }}" 
        state_class: total_increasing
        unit_of_measurement: "kWh" # string (optional, default: None)
        device_class: energy

```

**Comment by Tardisyuan** [comment]
感谢解惑 已经可以了 就是能源的数据显示很奇怪 应该是其他他问题了

**Comment by renhai-lab** [comment]
我试了好几次，`state_class`改为`total`和`total_increasing`都能放进能源面板里，但是不能正确反映用电情况，我看到原仓库作者的template是这样配置的，没有加入device_class字段：
```YAML
  - trigger:
      - platform: event
        event_type: "state_changed"
        event_data: 
          entity_id: sensor.last_electricity_usage
    sensor:
      - name: last_electricity_usage_entity
        unique_id: last_electricity_usage_entity
        state: "{{ states('sensor.last_electricity_usage') }}"
        state_class: measurement
        unit_of_measurement: "KWH"
```

**其实，国家电网的更新频率很慢，其实不适合放在以小时为单位的能源面板中，也不能分时段计算电价，能源面板中最好是放入家中所有计电设备比如智能插座**
