### ISSUE TITLE
你好，部署遇到问题

### ISSUE THREAD

**Issue by tianzpxyz** [renhai-lab/sgcc_electricity#26]
按照你说的方法docker部署不成功，能介绍下在portainer下如何部署吗？谢谢

**Comment by renhai-lab** [comment]
1. 在portainer中选择**Stacks>Add stack**，创建Create stack
>没有stack则需要升级portainer
![image](https://github.com/renhai-lab/sgcc_electricity/assets/130763230/ddff9c12-a024-478a-bfc8-63fbfad173a2)

2. 在Web editor 中填入以下docker-compose的文件并根据情况修改，具体说明见env文件的注释:
![image](https://github.com/renhai-lab/sgcc_electricity/assets/130763230/3cb9df1e-b2bb-4ccb-8e65-3a1165c6eb02)
```
version: "3"

services:
  app:
    depends_on:
      - mongo
    image: renhai/sgcc_electricity:1.3.3
    container_name: sgcc_electricity
    networks:
      - sgcc_network
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
      - PHONE_NUMBER="xxx"
      - PASSWORD="xxxx"
      - ENABLE_DATABASE_STORAGE=True
      - MONGO_URL="mongodb://USERNAME:PASSWORD@mongo-for-sgcc:27017/"
      - DB_NAME="homeassistant"
      - HASS_URL="http://localhost:8123/"
      - HASS_TOKEN="eyxxxxx"
      - JOB_START_TIME="07:00"
      - DRIVER_IMPLICITY_WAIT_TIME=60
      - RETRY_TIMES_LIMIT=5
      - LOGIN_EXPECTED_TIME=60
      - RETRY_WAIT_TIME_OFFSET_UNIT=10
      - FIRST_SLEEP_TIME=10
      - LOG_LEVEL="INFO"
    restart: unless-stopped
    command: python3 main.py

  mongo:
    image: mongo:4.4.18
    restart: always
    container_name: mongo-for-sgcc
    networks:
      - sgcc_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=PASSWORD
      - MONGODB_DATABASE=homeassistant
      - CONTAINER_TIMEZONE=Asia/Shanghai
    volumes:
      - ./db:/data/db

networks:
  sgcc_network:
```

3. 点击创建stack
4. 进入容器看是否创建成功
